### ISSUE TITLE
Create Event Page

### ISSUE THREAD

**Issue by EscapeManOZK** [CampusLandes/E-Campus#5]
This page is public
If the user is login, he can see all event (public and private), his invitation and all of event where he participate.

https://ng.ant.design/components/list/en

this is the list we use for see all of event

he will have some filter with : dropdown multiselection : https://ng.ant.design/components/select/en with value : 'private' 'public' 'participate' 'his Event'

If the user isn't login, he can see only public event

**Comment by MichaelM-campuslandes** [comment]
Pagination / Infinite Scroll
